#!/usr/bin/env bash
# Display a comprehensive list of running processes with hierarchy

echo "USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND"
ps -eo user,pid,pcpu,pmem,vsz,rss,tty,stat,start,time,command --forest
