#!/usr/bin/env bash
# Show PID and full executable path of bash processes without using ps

for pid in $(pgrep bash); do
  exe=$(cat "/proc/$pid/cmdline" | tr "\0" " " | awk "{print \$1}")
  echo "$pid $exe"
done
